// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '*',
    appId: '1:434009662467:web:4f86dcbb7e623440bc5a36',
    messagingSenderId: '434009662467',
    projectId: 'cs4080-20205-dart',
    authDomain: 'cs4080-20205-dart.firebaseapp.com',
    storageBucket: 'cs4080-20205-dart.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '*',
    appId: '1:434009662467:android:41f098da74bef3b9bc5a36',
    messagingSenderId: '434009662467',
    projectId: 'cs4080-20205-dart',
    storageBucket: 'cs4080-20205-dart.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '*',
    appId: '1:434009662467:web:207f1b57cc770618bc5a36',
    messagingSenderId: '434009662467',
    projectId: 'cs4080-20205-dart',
    authDomain: 'cs4080-20205-dart.firebaseapp.com',
    storageBucket: 'cs4080-20205-dart.firebasestorage.app',
  );
}
